version: "3"

services:
  postgres_1:
    image: postgres
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: postgres1
      POSTGRES_DB: postgres1
      PGPORT: 5432
    ports:
      - 5432:5432
    command: [ "postgres", "-c", "log_statement=all" ]

  postgres_2:
    image: postgres
    environment:
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: postgres2
      POSTGRES_DB: postgres2
      PGPORT: 5433
    ports:
      - 5433:5433
    command: [ "postgres", "-c", "log_statement=all" ]
